# Generated by Django 3.2.4 on 2021-07-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_stuffs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuffs',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stuffs',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
