# Generated by Django 3.2.4 on 2021-08-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_change_dates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Change_Dates',
        ),
    ]
