# Generated by Django 3.2.4 on 2021-06-24 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createteam', '0002_auto_20210623_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='User_Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
