# Generated by Django 3.2.4 on 2021-06-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0003_alter_player_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['firstname', 'lastname', 'team']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['team_name']},
        ),
    ]
