# Generated by Django 3.2.4 on 2021-07-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0004_auto_20210624_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['firstname', 'lastname']},
        ),
        migrations.RemoveField(
            model_name='player',
            name='post',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.CreateModel(
            name='Team_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50)),
                ('Team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createteam.team')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createteam.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, through='createteam.Team_Player', to='createteam.Team'),
        ),
    ]
