# Generated by Django 3.2.4 on 2021-07-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0005_auto_20210704_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(blank=True, through='createteam.Team_Player', to='createteam.Team'),
        ),
    ]
