# Generated by Django 3.2.4 on 2021-07-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0007_auto_20210704_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_player',
            old_name='Team',
            new_name='team',
        ),
    ]
