# Generated by Django 3.2.4 on 2021-07-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0008_rename_team_team_player_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_player',
            options={'ordering': ['post', 'player']},
        ),
    ]
