# Generated by Django 3.2.4 on 2021-08-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0010_user_team_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
