# Generated by Django 3.2.4 on 2021-08-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0011_player_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_team_change',
            name='number_of_changes_allowed',
            field=models.IntegerField(default=0),
        ),
    ]
