# Generated by Django 3.2.4 on 2021-08-16 06:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0015_league_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Player_League_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createteam.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createteam.player')),
            ],
        ),
    ]
