# Generated by Django 3.2.4 on 2021-08-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0016_auto_20210816_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='value',
            field=models.FloatField(default=6.6),
        ),
    ]
