# Generated by Django 3.2.4 on 2021-08-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0017_alter_player_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='allowed_to_change_format',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='league',
            name='allowed_to_change_format_range',
            field=models.IntegerField(default=0),
        ),
    ]
