# Generated by Django 3.2.4 on 2021-08-17 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0018_auto_20210817_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='allowed_to_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 16, 3, 6, 537340)),
        ),
        migrations.AlterField(
            model_name='league',
            name='allowed_to_create_date',
            field=models.DateTimeField(default=models.DateTimeField()),
        ),
    ]
