# Generated by Django 3.2.4 on 2021-08-17 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0020_alter_league_allowed_to_change_format_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='allowed_to_change_format_date',
        ),
        migrations.AddField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 16, 9, 13, 630519)),
        ),
    ]
