# Generated by Django 3.2.4 on 2021-08-19 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0025_alter_league_next_change_format_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='league_image',
        ),
        migrations.RemoveField(
            model_name='player',
            name='image_file_name',
        ),
        migrations.AddField(
            model_name='league',
            name='league_big_image',
            field=models.ImageField(default='', upload_to='images/leagues/big/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='league_small_image',
            field=models.ImageField(default='', upload_to='images/leagues/small/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='player_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/players/'),
        ),
        migrations.AlterField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 13, 30, 28, 81570)),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/teams/'),
        ),
    ]
