# Generated by Django 3.2.4 on 2021-08-19 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0028_alter_league_next_change_format_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 15, 32, 15, 175678)),
        ),
        migrations.CreateModel(
            name='League_Player_Change_Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ch_15', models.DateTimeField()),
                ('end_ch_15', models.DateTimeField()),
                ('start_ch_5', models.DateTimeField()),
                ('end_ch_5', models.DateTimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createteam.league')),
            ],
        ),
    ]
