# Generated by Django 3.2.4 on 2021-08-19 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0029_auto_20210819_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_League_score',
            new_name='League_Player_Score',
        ),
        migrations.AlterField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 15, 44, 14, 201416)),
        ),
    ]
