# Generated by Django 3.2.4 on 2021-08-23 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0033_auto_20210823_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='allow_to_change_format',
        ),
        migrations.AlterField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 16, 35, 38, 879154)),
        ),
    ]
