# Generated by Django 3.2.4 on 2021-08-23 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0034_auto_20210823_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='allowed_to_create_date',
            new_name='allow_to_create_date',
        ),
        migrations.RemoveField(
            model_name='league',
            name='allowed_to_change_format_range',
        ),
        migrations.AlterField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 16, 36, 44, 653230)),
        ),
    ]
