# Generated by Django 3.2.4 on 2021-08-23 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0035_auto_20210823_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='allow_to_create_date',
            new_name='allow_to_create_team_date',
        ),
        migrations.AlterField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 16, 37, 54, 740998)),
        ),
    ]
