# Generated by Django 3.2.4 on 2021-08-26 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0036_auto_20210823_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fullname',
            field=models.CharField(default='abc', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 12, 45, 45, 308656)),
        ),
        migrations.AlterField(
            model_name='player',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
