# Generated by Django 3.2.4 on 2021-08-26 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0037_auto_20210826_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_fullname',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 12, 50, 13, 514379)),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
    ]
