# Generated by Django 3.2.4 on 2021-08-29 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0038_auto_20210826_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 9, 57, 36, 851447)),
        ),
    ]
