# Generated by Django 3.2.4 on 2021-08-30 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0040_alter_league_next_change_format_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_reward',
            field=models.ImageField(blank=True, null=True, upload_to='images/leagues/reward/'),
        ),
        migrations.AlterField(
            model_name='league',
            name='next_change_format_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 14, 56, 11, 485255)),
        ),
    ]
