# Generated by Django 3.2.4 on 2021-07-04 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createteam', '0005_auto_20210704_1744'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_userprofile_is_team_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.JSONField(null=True)),
                ('team_format', models.JSONField(null=True)),
                ('main_players', models.JSONField(null=True)),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createteam.league')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
