# Generated by Django 3.2.4 on 2021-07-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_team',
            old_name='league_id',
            new_name='league',
        ),
        migrations.RenameField(
            model_name='user_team',
            old_name='user_id',
            new_name='user',
        ),
    ]
