# Generated by Django 3.2.4 on 2021-07-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210704_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_team',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
