# Generated by Django 3.2.4 on 2021-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_team_is_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_team',
            name='user_score',
            field=models.FloatField(default=0),
        ),
    ]
